# Panggil data

In [ ]:
# Menyambungkan ke drive
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
# Library pandas untuk membaca data .csv
import pandas as pd
data = pd.read_csv('/content/gdrive/My Drive/Dataset/Iris.csv')

In [ ]:
# Isi datanya
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
# Menghapus kolom id
data = data.drop(columns = ["Id"])

In [ ]:
# isi data setelah kolom id dihapus
data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# Membagi data training dan data testing
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']], data[["Species"]], test_size=0.2)

In [ ]:
# Bentuknya diubah menjadi array
import numpy as np
y_test = np.ravel(y_test)
y_train = np.ravel(y_train)
# dipakai hanya agar tidak ada warning

# Training model 1nn

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
# Membuat KNN Classifier
knn = KNeighborsClassifier(n_neighbors = 14)
# Fit  classifier ke data
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=14)

# Evaluasi model

In [ ]:
# Mengecek akurasi model pada data testing
knn.score(x_test, y_test)

1.0

In [ ]:
pred = np.array([5.1, 3.5, 1.4, 0.2])
pred = pred.reshape(1,4)

In [ ]:
knn.predict(pred)
#ternyata ini sukses tetapi hanya mengeluarkan warning, tetapi mendapatkan output yaitu Iris-setosa

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"

array(['Iris-setosa'], dtype=object)

In [ ]:
x_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
76             6.8           2.8            4.8           1.4
84             5.4           3.0            4.5           1.5
46             5.1           3.8            1.6           0.2
71             6.1           2.8            4.0           1.3
98             5.1           2.5            3.0           1.1
102            7.1           3.0            5.9           2.1
50             7.0           3.2            4.7           1.4
4              5.0           3.6            1.4           0.2
132            6.4           2.8            5.6           2.2
63             6.1           2.9            4.7           1.4
97             6.2           2.9            4.3           1.3
113            5.7           2.5            5.0           2.0
134            6.1           2.6            5.6           1.4
49             5.0           3.3            1.4           0.2
6              4.6           3.4            1.4           0.3
72             6.3           2.5            4.9           1.5
122            7.7           2.8            6.7           2.0
119            6.0           2.2            5.0           1.5
30             4.8           3.1            1.6           0.2
133            6.3           2.8            5.1           1.5
79             5.7           2.6            3.5           1.0
91             6.1           3.0            4.6           1.4
39             5.1           3.4            1.5           0.2
117            7.7           3.8            6.7           2.2
109            7.2           3.6            6.1           2.5
143            6.8           3.2            5.9           2.3
92             5.8           2.6            4.0           1.2
16             5.4           3.9            1.3           0.4
12             4.8           3.0            1.4           0.1
0              5.1           3.5            1.4           0.2

In [ ]:
data.loc[[143]]

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
143            6.8           3.2            5.9           2.3  Iris-virginica

In [ ]:
# Menampilkan hasil prediksi pada data testing index 143
knn.predict(x_test.loc[[143]])

array(['Iris-virginica'], dtype=object)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 7)
knn.fit(x_train, y_train)

# Testing
rightGuess = 0
falseGuess = 0
totalGuess = 0
for idx, row in x_test.iterrows():
    totalGuess+=1
    predict = knn.predict(x_test.loc[[idx]])[0]
    real = data.loc[[idx]]['Species'][idx]
    if(real == predict):
      rightGuess += 1
    else:
      falseGuess += 1

overallResult = "%.5f" %(rightGuess/(rightGuess + falseGuess))
print("Jumlah prediksi benar\t:", rightGuess, "")
print("Jumlah prediksi salah\t:", falseGuess)
print("Akurasi tes\t\t:", overallResult)

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000

In [ ]:
# Menampilkan akurasi dari k=1 sampai k=70
from sklearn.neighbors import KNeighborsClassifier

for k in range (1, 70):
  knn = KNeighborsClassifier(n_neighbors = k)
  knn.fit(x_train, y_train)

  rightGuess = 0
  falseGuess = 0
  for idx, row in x_test.iterrows():
      real = data.loc[[idx]]['Species'][idx]
      predict = knn.predict(x_test.loc[[idx]])[0]
      if(real == predict):
        rightGuess += 1
      else:
        falseGuess += 1

  print("=================KNN=================")
  print("Jumlah k untuk KNN \t:", k, "\n")
  overallResult = "%.5f" %(rightGuess/(rightGuess + falseGuess))
  print("Jumlah prediksi benar\t:", rightGuess, "")
  print("Jumlah prediksi salah\t:", falseGuess)
  print("Akurasi tes\t\t:", overallResult)

=================KNN=================
Jumlah k untuk KNN 	: 1

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 2

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 3

Jumlah prediksi benar	: 28
Jumlah prediksi salah	: 2
Akurasi tes		: 0.93333
=================KNN=================
Jumlah k untuk KNN 	: 4

Jumlah prediksi benar	: 28
Jumlah prediksi salah	: 2
Akurasi tes		: 0.93333
=================KNN=================
Jumlah k untuk KNN 	: 5

Jumlah prediksi benar	: 29
Jumlah prediksi salah	: 1
Akurasi tes		: 0.96667
=================KNN=================
Jumlah k untuk KNN 	: 6

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 7

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 8

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 9

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 10

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 11

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 12

Jumlah prediksi benar	: 29
Jumlah prediksi salah	: 1
Akurasi tes		: 0.96667
=================KNN=================
Jumlah k untuk KNN 	: 13

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 14

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 15

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 16

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 17

Jumlah prediksi benar	: 29
Jumlah prediksi salah	: 1
Akurasi tes		: 0.96667
=================KNN=================
Jumlah k untuk KNN 	: 18

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 19

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 20

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 21

Jumlah prediksi benar	: 30
Jumlah prediksi salah	: 0
Akurasi tes		: 1.00000
=================KNN=================
Jumlah k untuk KNN 	: 22

Jumlah prediksi benar	: 29
Jumlah prediksi salah	: 1
Akurasi tes		: 0.96667
=================KNN=================
Jumlah k untuk KNN 	: 23

Jumlah prediksi benar	: 29
Jumlah prediksi salah	: 1
Akurasi tes		: 0.96667
=================KNN=================
Jumlah k untuk KNN 	: 24

Jumlah prediksi benar	: 29
Jumlah prediksi salah	: 1
Akurasi tes		: 0.96667
=================KNN=================
Jumlah k untuk KNN 	: 25

Jumlah prediksi benar	: 29
Jumlah prediksi salah	: 1
Akurasi tes		: 0.96667
=================KNN=================
Jumlah k untuk KNN 	: 26

Jumlah prediksi benar	: 29
Jumlah prediksi salah	: 1
Akurasi tes		: 0.96667
=================KNN=================
Jumlah k untuk KNN 	: 27

Jumlah prediksi benar	: 28
Jumlah prediksi salah	: 2
Akurasi tes		: 0.93333
=================KNN=================
Jumlah k untuk KNN 	: 28

Jumlah prediksi benar	: 28
Jumlah prediksi salah	: 2
Akurasi tes		: 0.93333
=================KNN=================
Jumlah k untuk KNN 	: 29

Jumlah prediksi benar	: 29
Jumlah prediksi salah	: 1
Akurasi tes		: 0.96667
=================KNN=================
Jumlah k untuk KNN 	: 30

Jumlah prediksi benar	: 28
Jumlah prediksi salah	: 2
Akurasi tes		: 0.93333
=================KNN=================
Jumlah k untuk KNN 	: 31

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 32

Jumlah prediksi benar	: 28
Jumlah prediksi salah	: 2
Akurasi tes		: 0.93333
=================KNN=================
Jumlah k untuk KNN 	: 33

Jumlah prediksi benar	: 28
Jumlah prediksi salah	: 2
Akurasi tes		: 0.93333
=================KNN=================
Jumlah k untuk KNN 	: 34

Jumlah prediksi benar	: 28
Jumlah prediksi salah	: 2
Akurasi tes		: 0.93333
=================KNN=================
Jumlah k untuk KNN 	: 35

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 36

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 37

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 38

Jumlah prediksi benar	: 28
Jumlah prediksi salah	: 2
Akurasi tes		: 0.93333
=================KNN=================
Jumlah k untuk KNN 	: 39

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 40

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 41

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 42

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 43

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 44

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 45

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 46

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 47

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 48

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 49

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 50

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 51

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 52

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 53

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 54

Jumlah prediksi benar	: 27
Jumlah prediksi salah	: 3
Akurasi tes		: 0.90000
=================KNN=================
Jumlah k untuk KNN 	: 55

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 56

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 57

Jumlah prediksi benar	: 25
Jumlah prediksi salah	: 5
Akurasi tes		: 0.83333
=================KNN=================
Jumlah k untuk KNN 	: 58

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 59

Jumlah prediksi benar	: 25
Jumlah prediksi salah	: 5
Akurasi tes		: 0.83333
=================KNN=================
Jumlah k untuk KNN 	: 60

Jumlah prediksi benar	: 25
Jumlah prediksi salah	: 5
Akurasi tes		: 0.83333
=================KNN=================
Jumlah k untuk KNN 	: 61

Jumlah prediksi benar	: 25
Jumlah prediksi salah	: 5
Akurasi tes		: 0.83333
=================KNN=================
Jumlah k untuk KNN 	: 62

Jumlah prediksi benar	: 25
Jumlah prediksi salah	: 5
Akurasi tes		: 0.83333
=================KNN=================
Jumlah k untuk KNN 	: 63

Jumlah prediksi benar	: 25
Jumlah prediksi salah	: 5
Akurasi tes		: 0.83333
=================KNN=================
Jumlah k untuk KNN 	: 64

Jumlah prediksi benar	: 25
Jumlah prediksi salah	: 5
Akurasi tes		: 0.83333
=================KNN=================
Jumlah k untuk KNN 	: 65

Jumlah prediksi benar	: 25
Jumlah prediksi salah	: 5
Akurasi tes		: 0.83333
=================KNN=================
Jumlah k untuk KNN 	: 66

Jumlah prediksi benar	: 25
Jumlah prediksi salah	: 5
Akurasi tes		: 0.83333
=================KNN=================
Jumlah k untuk KNN 	: 67

Jumlah prediksi benar	: 25
Jumlah prediksi salah	: 5
Akurasi tes		: 0.83333
=================KNN=================
Jumlah k untuk KNN 	: 68

Jumlah prediksi benar	: 26
Jumlah prediksi salah	: 4
Akurasi tes		: 0.86667
=================KNN=================
Jumlah k untuk KNN 	: 69

Jumlah prediksi benar	: 25
Jumlah prediksi salah	: 5
Akurasi tes		: 0.83333

1. Saya coba iseng-iseng naikin k-nya sampai 10, hasil evaluasinya dapat akurasi 1.0, tapi saya rasa itu agak janggal. Kemudian saya coba prediksi dengan x_test[137], hasil tebakannya pun salah(Iris-virginica).

2. Tapi kalo saya buat looping dengan nilai k dari 1-10 untuk KNN, di angka k = 8 sudah mendapat akurasi 1.0 dan tebakannya benar semua(untuk 30 data di x_test)

3. Jadi, awalnya menurut nilai k saya yang paling baik adalah 7, karena kalau 8 sudah mendapatkan akurasi 1.0 dan itu cukup janggal(ML seharusnya tidak mencapai akurasi 100%)

4. Tapi di akhir, saya coba lagi train KNN sekali dengan k=10, dan tebakannya benar berkali-kali.

5. Jadi sepertinya saya mengambil nilai k = 8 sebagai tingkat k terbaik, karena jika 10 sepertinya berlebihan dan KNN malah bersifat menggeneralisir, bukannya klasifikasi.